# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['simplify']

# %% ../00_core.ipynb 3
from typing import Any, Dict, List, Tuple, Union

# %% ../00_core.ipynb 16
def simplify(obj: Any, key:Optional[str]=None):
    if type(obj) != dict:
        return obj
    r = {}
    for k, v in obj.items():
        if k == "def":
            r[key] = simplify(obj[k], k)
        else:
            r[f"{key}-{k}"] = simplify(obj[k], k)
    return r
