# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_europena.ipynb.

# %% auto 0
__all__ = []

# %% ../01_europena.ipynb 4
from typing import Any
from typing import Optional
from functools import lru_cache
from toolz import memoize
import io
from statistics import mean
from statistics import stdev
import xml.etree.ElementTree as ET
